// <auto-generated />
using System;
using EasySecuritiesManager.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EasySecuritiesManager.EntityFramework.Migrations
{
    [DbContext(typeof(EasySecuritiesManagerDBContext))]
    [Migration("20210426052017_initialSqlite")]
    partial class initialSqlite
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("EasySecuritiesManager.Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountHolderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountHolderId");

                    b.ToTable("tAccounts");
                });

            modelBuilder.Entity("EasySecuritiesManager.Domain.Models.AssetTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateProcessed")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPurchase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shares")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TheAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TheAccountId");

                    b.ToTable("tAssetTransactions");
                });

            modelBuilder.Entity("EasySecuritiesManager.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tUsers");
                });

            modelBuilder.Entity("EasySecuritiesManager.Domain.Models.Account", b =>
                {
                    b.HasOne("EasySecuritiesManager.Domain.Models.User", "AccountHolder")
                        .WithMany()
                        .HasForeignKey("AccountHolderId");

                    b.Navigation("AccountHolder");
                });

            modelBuilder.Entity("EasySecuritiesManager.Domain.Models.AssetTransaction", b =>
                {
                    b.HasOne("EasySecuritiesManager.Domain.Models.Account", "TheAccount")
                        .WithMany("AssetTransactions")
                        .HasForeignKey("TheAccountId");

                    b.OwnsOne("EasySecuritiesManager.Domain.Models.Asset", "TheAsset", b1 =>
                        {
                            b1.Property<int>("AssetTransactionId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("DayHigh")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("DayLow")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("MarketCap")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("PricePerShare")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Symbol")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("TimeOfFetch")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("YearHigh")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("YearLow")
                                .HasColumnType("TEXT");

                            b1.HasKey("AssetTransactionId");

                            b1.ToTable("tAssetTransactions");

                            b1.WithOwner()
                                .HasForeignKey("AssetTransactionId");
                        });

                    b.Navigation("TheAccount");

                    b.Navigation("TheAsset");
                });

            modelBuilder.Entity("EasySecuritiesManager.Domain.Models.Account", b =>
                {
                    b.Navigation("AssetTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
